// StyleSheetGenerator.cpp - Generate QSS from DesignTokens
#include "StyleSheetGenerator.h"
#include "ThemeManager.h"

namespace MegaCustom {

const ThemeManager& StyleSheetGenerator::tm()
{
    return ThemeManager::instance();
}

QString StyleSheetGenerator::colorHex(const QColor& color)
{
    return color.name();
}

QString StyleSheetGenerator::colorRgba(const QColor& color)
{
    return QString("rgba(%1, %2, %3, %4)")
        .arg(color.red())
        .arg(color.green())
        .arg(color.blue())
        .arg(color.alphaF(), 0, 'f', 2);
}

QString StyleSheetGenerator::generate()
{
    return generate(ThemeManager::instance().currentTheme());
}

QString StyleSheetGenerator::generate(ThemeManager::Theme theme)
{
    // Temporarily set theme if different (restore at end)
    ThemeManager::Theme originalTheme = ThemeManager::instance().currentTheme();
    if (theme != originalTheme && theme != ThemeManager::System) {
        const_cast<ThemeManager&>(ThemeManager::instance()).setTheme(theme);
    }

    QString qss;
    qss += "/* Generated by StyleSheetGenerator */\n\n";
    qss += generateButtonStyles();
    qss += generateMenuStyles();
    qss += generateScrollBarStyles();
    qss += generateInputStyles();
    qss += generateTableStyles();
    qss += generateTreeViewStyles();
    qss += generateTabStyles();
    qss += generateToolTipStyles();
    qss += generateProgressBarStyles();
    qss += generateDialogStyles();
    qss += generateSidebarStyles();
    qss += generateStatusBadgeStyles();
    qss += generateNotificationStyles();

    // Restore original theme if changed
    if (theme != originalTheme && theme != ThemeManager::System) {
        const_cast<ThemeManager&>(ThemeManager::instance()).setTheme(originalTheme);
    }

    return qss;
}

QString StyleSheetGenerator::generateButtonStyles()
{
    QString qss;

    // Primary button (type="primary")
    qss += QString(R"(
/* Primary Buttons */
QPushButton[type="primary"] {
    background-color: %1;
    color: %2;
    border: none;
    border-radius: 6px;
    padding: 6px 16px;
    font-weight: 600;
    min-height: 36px;
}
QPushButton[type="primary"]:hover {
    background-color: %3;
}
QPushButton[type="primary"]:pressed {
    background-color: %4;
}
QPushButton[type="primary"]:disabled {
    background-color: %5;
    color: %6;
}
)")
    .arg(colorHex(tm().buttonPrimary()))
    .arg(colorHex(tm().color("text-inverse")))
    .arg(colorHex(tm().buttonPrimaryHover()))
    .arg(colorHex(tm().buttonPrimaryPressed()))
    .arg(colorHex(tm().buttonDisabled()))
    .arg(colorHex(tm().textDisabled()));

    // Secondary button (type="secondary")
    qss += QString(R"(
/* Secondary Buttons */
QPushButton[type="secondary"] {
    background-color: %1;
    color: %2;
    border: none;
    border-radius: 6px;
    padding: 6px 16px;
    font-weight: 500;
    min-height: 36px;
}
QPushButton[type="secondary"]:hover {
    background-color: %3;
}
QPushButton[type="secondary"]:pressed {
    background-color: %4;
}
QPushButton[type="secondary"]:disabled {
    background-color: %5;
    color: %6;
}
)")
    .arg(colorRgba(tm().buttonSecondary()))
    .arg(colorHex(tm().textPrimary()))
    .arg(colorRgba(tm().buttonSecondaryHover()))
    .arg(colorRgba(tm().buttonSecondaryPressed()))
    .arg(colorRgba(tm().buttonDisabled()))
    .arg(colorHex(tm().textDisabled()));

    // Outline button (type="outline")
    qss += QString(R"(
/* Outline Buttons */
QPushButton[type="outline"] {
    background-color: transparent;
    color: %1;
    border: 1px solid %2;
    border-radius: 6px;
    padding: 6px 16px;
    font-weight: 500;
    min-height: 36px;
}
QPushButton[type="outline"]:hover {
    background-color: rgba(0, 0, 0, 0.05);
}
QPushButton[type="outline"]:pressed {
    background-color: rgba(0, 0, 0, 0.1);
}
QPushButton[type="outline"]:disabled {
    border-color: %3;
    color: %4;
}
)")
    .arg(colorHex(tm().textPrimary()))
    .arg(colorHex(tm().borderStrong()))
    .arg(colorHex(tm().borderSubtle()))
    .arg(colorHex(tm().textDisabled()));

    // Brand/Destructive button (type="destructive")
    qss += QString(R"(
/* Destructive Buttons */
QPushButton[type="destructive"] {
    background-color: %1;
    color: white;
    border: none;
    border-radius: 6px;
    padding: 6px 16px;
    font-weight: 600;
    min-height: 36px;
}
QPushButton[type="destructive"]:hover {
    background-color: %2;
}
QPushButton[type="destructive"]:pressed {
    background-color: %3;
}
)")
    .arg(colorHex(tm().supportError()))
    .arg(colorHex(tm().supportError().darker(110)))
    .arg(colorHex(tm().supportError().darker(120)));

    return qss;
}

QString StyleSheetGenerator::generateMenuStyles()
{
    return QString(R"(
/* Context Menus */
QMenu {
    background-color: %1;
    border: 1px solid %2;
    border-radius: 8px;
    padding: 4px 0px;
}
QMenu::item {
    background-color: transparent;
    color: %3;
    padding: 8px 16px 8px 12px;
    margin: 0px 4px;
    border-radius: 4px;
    min-width: 120px;
}
QMenu::item:selected {
    background-color: rgba(0, 0, 0, 0.05);
}
QMenu::item:disabled {
    color: %4;
}
QMenu::separator {
    height: 1px;
    background-color: %5;
    margin: 4px 8px;
}
QMenu::icon {
    padding-left: 8px;
}
)")
    .arg(colorHex(tm().surface1()))
    .arg(colorHex(tm().borderStrong()))
    .arg(colorHex(tm().textPrimary()))
    .arg(colorHex(tm().textSecondary()))
    .arg(colorHex(tm().borderSubtle()));
}

QString StyleSheetGenerator::generateScrollBarStyles()
{
    QString trackColor = tm().isDarkMode() ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.05)";
    QString handleColor = tm().isDarkMode() ? "rgba(255,255,255,0.3)" : "rgba(0,0,0,0.3)";
    QString handleHover = tm().isDarkMode() ? "rgba(255,255,255,0.5)" : "rgba(0,0,0,0.5)";

    return QString(R"(
/* Scrollbars */
QScrollBar:vertical {
    background-color: %1;
    width: 10px;
    margin: 0px;
    border-radius: 5px;
}
QScrollBar::handle:vertical {
    background-color: %2;
    min-height: 30px;
    border-radius: 5px;
    margin: 2px;
}
QScrollBar::handle:vertical:hover {
    background-color: %3;
}
QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
    height: 0px;
}
QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {
    background: none;
}

QScrollBar:horizontal {
    background-color: %1;
    height: 10px;
    margin: 0px;
    border-radius: 5px;
}
QScrollBar::handle:horizontal {
    background-color: %2;
    min-width: 30px;
    border-radius: 5px;
    margin: 2px;
}
QScrollBar::handle:horizontal:hover {
    background-color: %3;
}
QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {
    width: 0px;
}
QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {
    background: none;
}
)")
    .arg(trackColor)
    .arg(handleColor)
    .arg(handleHover);
}

QString StyleSheetGenerator::generateInputStyles()
{
    return QString(R"(
/* Line Edits */
QLineEdit {
    background-color: %1;
    color: %2;
    border: 1px solid %3;
    border-radius: 6px;
    padding: 8px 12px;
    selection-background-color: %4;
}
QLineEdit:focus {
    border-color: %5;
}
QLineEdit:disabled {
    background-color: %6;
    color: %7;
}
QLineEdit[readOnly="true"] {
    background-color: %6;
}

/* Combo Boxes */
QComboBox {
    background-color: %1;
    color: %2;
    border: 1px solid %3;
    border-radius: 6px;
    padding: 8px 12px;
    min-height: 20px;
}
QComboBox:hover {
    border-color: %5;
}
QComboBox::drop-down {
    border: none;
    width: 24px;
}
QComboBox QAbstractItemView {
    background-color: %1;
    border: 1px solid %3;
    border-radius: 6px;
    selection-background-color: %4;
}

/* Spin Boxes */
QSpinBox, QDoubleSpinBox {
    background-color: %1;
    color: %2;
    border: 1px solid %3;
    border-radius: 6px;
    padding: 6px 8px;
}
)")
    .arg(colorHex(tm().surface1()))
    .arg(colorHex(tm().textPrimary()))
    .arg(colorHex(tm().borderSubtle()))
    .arg(colorRgba(tm().brandDefault().lighter(150)))
    .arg(colorHex(tm().brandDefault()))
    .arg(colorHex(tm().surface2()))
    .arg(colorHex(tm().textDisabled()));
}

QString StyleSheetGenerator::generateTableStyles()
{
    return QString(R"(
/* Tables */
QTableView, QTableWidget {
    background-color: %1;
    alternate-background-color: %2;
    color: %3;
    border: 1px solid %4;
    border-radius: 6px;
    gridline-color: %5;
    selection-background-color: %6;
}
QTableView::item, QTableWidget::item {
    padding: 8px;
}
QTableView::item:selected, QTableWidget::item:selected {
    background-color: %6;
    color: %3;
}
QHeaderView::section {
    background-color: %2;
    color: %3;
    padding: 8px;
    border: none;
    border-bottom: 1px solid %4;
    font-weight: 600;
}
)")
    .arg(colorHex(tm().surface1()))
    .arg(colorHex(tm().surface2()))
    .arg(colorHex(tm().textPrimary()))
    .arg(colorHex(tm().borderSubtle()))
    .arg(colorHex(tm().borderSubtle()))
    .arg(colorRgba(tm().brandDefault().lighter(170)));
}

QString StyleSheetGenerator::generateTreeViewStyles()
{
    return QString(R"(
/* Tree Views */
QTreeView {
    background-color: %1;
    color: %2;
    border: 1px solid %3;
    border-radius: 6px;
    selection-background-color: %4;
}
QTreeView::item {
    padding: 6px 4px;
    border-radius: 4px;
    margin: 1px 2px;
}
QTreeView::item:hover {
    background-color: rgba(0, 0, 0, 0.03);
}
QTreeView::item:selected {
    background-color: %4;
}
QTreeView::branch:has-children:!has-siblings:closed,
QTreeView::branch:closed:has-children:has-siblings {
    border-image: none;
    image: url(:/icons/arrow-right.svg);
}
QTreeView::branch:open:has-children:!has-siblings,
QTreeView::branch:open:has-children:has-siblings {
    border-image: none;
    image: url(:/icons/arrow-down.svg);
}
)")
    .arg(colorHex(tm().surface1()))
    .arg(colorHex(tm().textPrimary()))
    .arg(colorHex(tm().borderSubtle()))
    .arg(colorRgba(tm().brandDefault().lighter(170)));
}

QString StyleSheetGenerator::generateTabStyles()
{
    return QString(R"(
/* Tab Widgets */
QTabWidget::pane {
    background-color: %1;
    border: 1px solid %2;
    border-radius: 6px;
    margin-top: -1px;
}
QTabBar::tab {
    background-color: transparent;
    color: %3;
    padding: 10px 16px;
    border-bottom: 2px solid transparent;
    margin-right: 4px;
}
QTabBar::tab:hover {
    color: %4;
}
QTabBar::tab:selected {
    color: %5;
    border-bottom-color: %5;
}
)")
    .arg(colorHex(tm().surface1()))
    .arg(colorHex(tm().borderSubtle()))
    .arg(colorHex(tm().textSecondary()))
    .arg(colorHex(tm().textPrimary()))
    .arg(colorHex(tm().brandDefault()));
}

QString StyleSheetGenerator::generateToolTipStyles()
{
    return QString(R"(
/* Tooltips */
QToolTip {
    background-color: %1;
    color: %2;
    border: 1px solid %3;
    border-radius: 4px;
    padding: 6px 10px;
}
)")
    .arg(colorHex(tm().surface3()))
    .arg(colorHex(tm().textPrimary()))
    .arg(colorHex(tm().borderStrong()));
}

QString StyleSheetGenerator::generateProgressBarStyles()
{
    return QString(R"(
/* Progress Bars */
QProgressBar {
    background-color: %1;
    border: none;
    border-radius: 4px;
    height: 8px;
    text-align: center;
}
QProgressBar::chunk {
    background-color: %2;
    border-radius: 4px;
}
)")
    .arg(colorHex(tm().surface2()))
    .arg(colorHex(tm().brandDefault()));
}

QString StyleSheetGenerator::generateDialogStyles()
{
    return QString(R"(
/* Dialogs */
QDialog {
    background-color: %1;
    color: %2;
}
QDialog QLabel {
    color: %2;
}
QDialog QLabel[type="title"] {
    font-size: 16px;
    font-weight: 600;
    color: %2;
}
QDialog QLabel[type="subtitle"] {
    font-size: 13px;
    color: %3;
}

/* Group Boxes */
QGroupBox {
    background-color: transparent;
    border: 1px solid %4;
    border-radius: 6px;
    margin-top: 12px;
    padding-top: 8px;
    font-weight: 600;
}
QGroupBox::title {
    subcontrol-origin: margin;
    subcontrol-position: top left;
    padding: 0 8px;
    color: %2;
}
)")
    .arg(colorHex(tm().surface1()))
    .arg(colorHex(tm().textPrimary()))
    .arg(colorHex(tm().textSecondary()))
    .arg(colorHex(tm().borderSubtle()));
}

QString StyleSheetGenerator::generateSidebarStyles()
{
    return QString(R"(
/* Sidebar */
#MegaSidebar {
    background-color: %1;
    border-right: 1px solid %2;
}
#MegaSidebar QLabel#logoLabel {
    padding: 16px;
    font-size: 18px;
    font-weight: 700;
    color: %3;
}

/* Navigation Buttons */
#MegaSidebar QPushButton {
    background-color: transparent;
    color: %4;
    border: none;
    border-radius: 6px;
    padding: 10px 16px;
    text-align: left;
    font-size: 13px;
}
#MegaSidebar QPushButton:hover {
    background-color: %5;
}
#MegaSidebar QPushButton:checked,
#MegaSidebar QPushButton[active="true"] {
    background-color: %6;
    color: %3;
    font-weight: 600;
}

/* Storage Bar */
#MegaSidebar QProgressBar {
    background-color: %7;
    border: none;
    border-radius: 3px;
    height: 6px;
}
#MegaSidebar QProgressBar::chunk {
    background-color: %3;
    border-radius: 3px;
}
)")
    .arg(colorHex(tm().surface1()))
    .arg(colorHex(tm().borderSubtle()))
    .arg(colorHex(tm().brandDefault()))
    .arg(colorHex(tm().textSecondary()))
    .arg(tm().isDarkMode() ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.05)")
    .arg(tm().isDarkMode() ? "rgba(255,255,255,0.1)" : "rgba(0,0,0,0.08)")
    .arg(colorHex(tm().surface2()));
}

QString StyleSheetGenerator::generateStatusBadgeStyles()
{
    return QString(R"(
/* Status Badges */
QLabel[status="ready"], QLabel[status="success"] {
    background-color: %1;
    color: white;
    border-radius: 10px;
    padding: 4px 10px;
    font-size: 11px;
    font-weight: 600;
}
QLabel[status="syncing"], QLabel[status="active"] {
    background-color: %2;
    color: white;
    border-radius: 10px;
    padding: 4px 10px;
    font-size: 11px;
    font-weight: 600;
}
QLabel[status="paused"], QLabel[status="warning"] {
    background-color: %3;
    color: white;
    border-radius: 10px;
    padding: 4px 10px;
    font-size: 11px;
    font-weight: 600;
}
QLabel[status="failed"], QLabel[status="error"] {
    background-color: %4;
    color: white;
    border-radius: 10px;
    padding: 4px 10px;
    font-size: 11px;
    font-weight: 600;
}
QLabel[status="pending"], QLabel[status="inactive"] {
    background-color: %5;
    color: white;
    border-radius: 10px;
    padding: 4px 10px;
    font-size: 11px;
    font-weight: 600;
}
)")
    .arg(colorHex(tm().supportSuccess()))
    .arg(colorHex(tm().supportInfo()))
    .arg(colorHex(tm().supportWarning()))
    .arg(colorHex(tm().supportError()))
    .arg(colorHex(tm().textSecondary()));
}

QString StyleSheetGenerator::generateNotificationStyles()
{
    return QString(R"(
/* Notification Boxes */
QFrame[notification="info"] {
    background-color: %1;
    border: 1px solid %2;
    border-radius: 6px;
    padding: 12px;
}
QFrame[notification="info"] QLabel {
    color: %3;
}

QFrame[notification="success"] {
    background-color: %4;
    border: 1px solid %5;
    border-radius: 6px;
    padding: 12px;
}
QFrame[notification="success"] QLabel {
    color: %6;
}

QFrame[notification="warning"] {
    background-color: %7;
    border: 1px solid %8;
    border-radius: 6px;
    padding: 12px;
}
QFrame[notification="warning"] QLabel {
    color: %9;
}

QFrame[notification="error"] {
    background-color: %10;
    border: 1px solid %11;
    border-radius: 6px;
    padding: 12px;
}
QFrame[notification="error"] QLabel {
    color: %12;
}
)")
    .arg(colorHex(tm().color("notification-info")))
    .arg(colorHex(tm().supportInfo()))
    .arg(colorHex(tm().color("text-info")))
    .arg(colorHex(tm().color("notification-success")))
    .arg(colorHex(tm().supportSuccess()))
    .arg(colorHex(tm().color("text-success")))
    .arg(colorHex(tm().color("notification-warning")))
    .arg(colorHex(tm().supportWarning()))
    .arg(colorHex(tm().color("text-warning")))
    .arg(colorHex(tm().color("notification-error")))
    .arg(colorHex(tm().supportError()))
    .arg(colorHex(tm().color("text-error")));
}

} // namespace MegaCustom
